apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker-scheduled-processing
  namespace: bitcoin-hooks-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: gcr.io/zapgo-1273/bitcoin-hooks:v0.022
        imagePullPolicy: IfNotPresent
        name: bitcoin-hooks
        ports:
        - containerPort: 8000
        command: ['bash','-c', 'celery -A config.celery worker --loglevel=INFO --concurrency=1 -Q scheduled-processing-bitcoin-kube-staging']
        envFrom:
          - secretRef:
              name: bitcoin-hooks
          - configMapRef:
              name: bitcoin-hooks
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker-notify-new-txs
  namespace: bitcoin-hooks-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: gcr.io/zapgo-1273/bitcoin-hooks:v0.022
        imagePullPolicy: IfNotPresent
        name: bitcoin-hooks
        ports:
        - containerPort: 8000
        command: ['bash','-c', 'celery -A config.celery worker --loglevel=INFO --concurrency=1 -Q notify-new-txs-bitcoin-kube-staging']
        envFrom:
          - secretRef:
              name: bitcoin-hooks
          - configMapRef:
              name: bitcoin-hooks
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker-notify-confirmations
  namespace: bitcoin-hooks-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: gcr.io/zapgo-1273/bitcoin-hooks:v0.022
        imagePullPolicy: IfNotPresent
        name: bitcoin-hooks
        ports:
        - containerPort: 8000
        command: ['bash','-c', 'celery -A config.celery worker --loglevel=INFO --concurrency=1 -Q notify-confirmations-bitcoin-kube-staging']
        envFrom:
          - secretRef:
              name: bitcoin-hooks
          - configMapRef:
              name: bitcoin-hooks
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker-send-webhooks
  namespace: bitcoin-hooks-staging
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: gcr.io/zapgo-1273/bitcoin-hooks:v0.022
        imagePullPolicy: IfNotPresent
        name: bitcoin-hooks
        ports:
        - containerPort: 8000
        command: ['bash','-c', 'celery -A config.celery worker --loglevel=INFO --concurrency=1 -Q send-webhooks-bitcoin-kube-staging']
        envFrom:
          - secretRef:
              name: bitcoin-hooks
          - configMapRef:
              name: bitcoin-hooks