version: "2.1"

services:
  webapp:
    image: ${IMAGE_NAME}
    user: webapp
    env_file: ${PWD}/${ENV_FILE}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    restart: always
