# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-10 19:43
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import stokvel.models


class Migration(migrations.Migration):

    dependencies = [
        ('stokvel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payout',
            field=stokvel.models.MoneyField(decimal_places=18, default=Decimal('0'), max_digits=28),
        ),
    ]
