# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-10 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stokvel', '0003_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
