# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stokvel', '0005_auto_20170614_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='stokvel',
        ),
        migrations.AddField(
            model_name='vote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stokvel.Event'),
            preserve_default=False,
        ),
    ]
