# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stokvel', '0006_auto_20170625_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stokvel.User'),
            preserve_default=False,
        ),
    ]
